name: Build UWP App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Install Required Components
      run: |
        # Установка компонентов через VS Installer
        $installerPath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        $vsPath = & $installerPath -latest -property installationPath
        & "$vsPath\Common7\Tools\VsDevCmd.bat" -no_logo &&
        & "$vsPath\Common7\IDE\VSInstaller.exe" modify `
          --installPath "$vsPath" `
          --add Microsoft.VisualStudio.Component.Windows10SDK.18362 `
          --add Microsoft.VisualStudio.ComponentGroup.UWP.Support `
          --quiet --norestart --wait

    - name: Restore NuGet packages
      run: nuget restore Whisp.csproj

    - name: Build project
      run: |
        msbuild Whisp.csproj /p:Configuration=Release /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload /p:AppxBundlePlatforms="x86|x64|ARM"

    - name: Create self-signed certificate
      run: |
        $cert = New-SelfSignedCertificate -Type Custom -Subject "CN=Whisp" -KeyUsage DigitalSignature -FriendlyName "Whisp" -CertStoreLocation "Cert:\CurrentUser\My" -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3", "2.5.29.19={text}")
        $certPath = "Cert:\CurrentUser\My\$($cert.Thumbprint)"
        Export-PfxCertificate -Cert $certPath -FilePath "Whisp.pfx" -Password (ConvertTo-SecureString -String "password" -Force -AsPlainText)

    - name: Sign the app package
      run: |
        $pfxPath = "Whisp.pfx"
        $appxPackage = Get-ChildItem -Path ".\AppPackages" -Filter "*.appx" -Recurse | Select-Object -First 1
        & "C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\signtool.exe" sign /fd SHA256 /a /f $pfxPath /p "password" $appxPackage.FullName

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: appx-package
        path: AppPackages
