name: Build UWP App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Install Windows 10 SDK
      run: |
        # Проверяем доступные версии Windows SDK
        Get-ChildItem "C:\Program Files (x86)\Windows Kits\10\bin" | Select-Object Name
        
        # Используем VSWhere для поиска установленных компонентов
        $installerPath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
        $vsPath = & $installerPath -latest -property installationPath
        
        # Проверяем доступные рабочие нагрузки
        & "$vsPath\Common7\Tools\VsDevCmd.bat" -no_logo
        & "$vsPath\Common7\IDE\vs_installer.exe" modify `
          --installPath "$vsPath" `
          --add Microsoft.VisualStudio.Component.Windows10SDK `
          --add Microsoft.VisualStudio.ComponentGroup.UWP.Support `
          --quiet --norestart --wait

    - name: Verify Windows SDK installation
      run: |
        if (Test-Path "C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\makeappx.exe") {
          echo "Windows 10 SDK 18362 found"
        } else {
          echo "Windows 10 SDK 18362 not found"
          exit 1
        }

    - name: Restore NuGet packages
      run: nuget restore Whisp.csproj

    - name: Build project
      run: |
        msbuild Whisp.csproj /p:Configuration=Release /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload /p:AppxBundlePlatforms="x86|x64|ARM"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: appx-package
        path: AppPackages
